### ISSUE TITLE
Get competitor.id from IOutcomeOdds?

### ISSUE THREAD

**Issue by mijkathegreat** [sportradar/UnifiedOddsSdkNetCore#14]
Hello!
We're trying to find a way to get Competitor.Id from OutcomeOdds (for 'tournament winner' market), but didn't find it without reflection (with reflection we can get NameProvider and get _profileCache from it).
We cannot use Outcome.Name as team/competitor id because it's unreliable way for sure (we want to make some matching from OutcomeOdds to Competitor object).

Could u please suggest some good way to do this?

**Comment by dhrovat** [comment]
Hi,
I am not sure I understand what you want, but each market/outcome is linked to event received in the feed message. On the event there is an method to get competitors.
The other way to receive competitor data is via ISportDataProvider.GetCompetitorAsync(...)

**Comment by dhrovat** [comment]
No feedback in 3 weeks.
