### ISSUE TITLE
Can't find sport_event_status in IOddsChange<ISportEvent> class

### ISSUE THREAD

**Issue by hotyes** [sportradar/UnifiedOddsSdkNetCore#16]
Hi, as the document here: https://docs.betradar.com/display/BD/UOF+-+Sport+event+status

the odds change message should has `sport_event_status ` attribute, but it seems this SDK doesn't provide it. may I know how I can get sport_event_status  from odds change message

**Comment by dhrovat** [comment]
You need to cast ISportEvent to appropriate class, like IMatch, IStage, ISoccerEvent and on there you can access SportEventStatus.
