### ISSUE TITLE
Library on nuget is built in DEBUG mode

### ISSUE THREAD

**Issue by micdenny** [sportradar/UnifiedOddsSdkNetCore#20]
When I was investigating the problem on #19 the exception message took my attention, I saw a `DebugProvider` in it, does the DLL be compiled in DEBUG mode? Is there a reason for that?

This is took from the `v1.27.0` package:

![image](https://user-images.githubusercontent.com/1633595/190213942-84cd4573-46ef-428b-b983-ff166fb3f62d.png)

![image](https://user-images.githubusercontent.com/1633595/190214159-18f77c7e-dc6a-48c8-bb6f-f9a59a4f25fa.png)

**Comment by dhrovat** [comment]
Some Debug.Asserts was removed version 1.28.0, so upgrading would avoid this.
But as for what we have release package with debug mode dll - in the past that was specifically requested by some customers. 
Currently we are implementing new pipeline which will generate packages in Release mode, so any future release will change that.

**Comment by dhrovat** [comment]
The release pipeline was changed in between, so new packages are published in Release mode.
