### ISSUE TITLE
How to subscribe specified sports instead of all messages

### ISSUE THREAD

**Issue by hotyes** [sportradar/UnifiedOddsSdkNetCore#23]
I am trying to use MessageInterest but it seems no way to create this pattern 

`"-.-.-.-.SportId.-.-.-"`

thanks

**Comment by dhrovat** [comment]
Currently this is not possible. I have added this recommendation to our sdk feature list and we will see if it will be prioritized.
The workaround for now is to subscribe to all and filter it out based on the sport associated with the message, not ideal.
