### ISSUE TITLE
Best practices of  manage the sports event cache

### ISSUE THREAD

**Issue by hotyes** [sportradar/UnifiedOddsSdkNetCore#24]
Hi @dhrovat the SDK use a timer to delete sports event from cache by every 12 hours, but it seems is not configurable, is it a recommended settings? any other way to manage the cache?

**Comment by dhrovat** [comment]
Currently sdk does not expose option to change internal expiration time for cache items in SportEventCache (only competitor and player profile cache does - via OperationManager), and variant market description cache.
The option is to delete eventids from cache via SportDataProvider, it can be done 1 by 1 or for all which have schedule date before some date.
