### ISSUE TITLE
Whats the change for v1.29.0

### ISSUE THREAD

**Issue by hotyes** [sportradar/UnifiedOddsSdkNetCore#25]
Hi there, I just saw there is a new version v1.29.0 on nuget, but this repo haven't update, might I know whats the change for this release? thanks

**Comment by dhrovat** [comment]
Hi,
yes, we are in the process of changing internal pipeline and changes from one git to this one are not yet visible.
The changelog can be viewed on sdk.sportradar.com, but for v1.29.0 is:
Enabled BookingStatus for stages fetches fixture
Fix for variant market descriptions (to ignore default static market description - effects playerprops markets)
Fix for fetching missing summary only if required (effects ILongTermEvent entities)

**Comment by dhrovat** [comment]
New version (v1.30.1) was published to nuget.org. Also the code was updated to match the published version.
