### ISSUE TITLE
Logging level of 'Transforming CompetitorCI'

### ISSUE THREAD

**Issue by kerams** [sportradar/UnifiedOddsSdkNetCore#3]
Do these types of messages really need to be warnings? There's quite a lot of them being logged, yet I'm not sure what value they bring. Maybe consider downgrading them to Debug?
`2020-03-04T13:46:50.1033287+01:00  [WRN] Transforming CompetitorCI to TeamCompetitorCI for sr:competitor:1678 (67fe0812)`

**Comment by dhrovat** [comment]
Hi, have lowered it to debug level. Will be available in next release.
