### ISSUE TITLE
Useless need of lock around MemoryCache that is thread safe

### ISSUE THREAD

**Issue by micdenny** [sportradar/UnifiedOddsSdkNetCore#5]
The lock around `System.Runtime.Caching.MemoryCache` is not needed because [`MemoryCache` is thread safe](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.caching.memorycache?view=dotnet-plat-ext-3.1#thread-safety).

https://github.com/sportradar/UnifiedOddsSdkNetCore/blob/43f34aa4b901f64395c1af00d09465f687556806/src/Sportradar.OddsFeed.SDK/Entities/REST/Internal/Caching/SportEventStatusCache.cs#L116-L125

I didn't check all the source code, but I've found it in [SportEventStatusCache](https://github.com/sportradar/UnifiedOddsSdkNetCore/blob/master/src/Sportradar.OddsFeed.SDK/Entities/REST/Internal/Caching/SportEventStatusCache.cs) and I wanted to point it out.

**Comment by dhrovat** [comment]
Thank you for pointing that out. Lock was cleaned up. Will be available in next release.
